services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" # console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  file-upload-db:
    image: postgres:latest
    ports:
      # host_port:container_port
      - "5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - file-upload-db-data:/var/lib/postgresql

  file-upload-service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://dev:password@file-upload-db:5432/dev_db
    depends_on:
      - minio
      - file-upload-db

volumes:
  minio_data:
  file-upload-db-data:
