name: Workspace Microservice CI

on:
  pull_request:
    branches: [ "main" ]
    paths: 'services/workspace/**'

jobs:
  build:
    name: Workspace CI Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/workspace

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.6'

      - name: Format check
        run: go fmt ./... && git diff --exit-code

      - name: Static analysis check
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          working-directory: services/workspace

      - name: Build check
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install SQLFluff
        run: |
          pip install sqlfluff

      - name: Run SQLFluff lint
        run: |
          sqlfluff lint . --dialect postgres